### ISSUE TITLE
sorting by data type (currently numbers are treated as strings)

### ISSUE THREAD

**Issue by tkakar** [linmasahiro/vue3-table-lite#47]
This is a great package, just have a comment.
Currently, the sort function treats numbers as string as well. For example, for numbers 1-20, the sorting will show 1, 10, 11, 12 ...
 Is there any way to specify if the type is numeric. Appreciate it.

**Comment by linmasahiro** [comment]
Hi, @tkakar 
Thanks your advice.
I am referenced the MDN and tried fixed the bug. It's looks good working...
```
let rows = props.rows;
// refs https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/compare
var collator = new Intl.Collator(undefined, {
  numeric: true,
  sensitivity: "base",
});
let sortOrder = setting.sort === "desc" ? -1 : 1;
rows.sort(function (a, b) {
  return collator.compare(a[setting.order], b[setting.order]) * sortOrder;
});
```

**Comment by tkakar** [comment]
@linmasahiro Thank you. this was very quick. sorry to bug again. the sorting does not work for decimals now. It works for strings and numbers. Really appreciate your promptness.

**Comment by linmasahiro** [comment]
Hi, @tkakar 

> the sorting does not work for decimals now

I am tried to sorting decimals and it's good working. Maybe you can give me any example to solve the problem or check your 'vue3-table-lite' source was upgrade to [latest](https://github.com/linmasahiro/vue3-table-lite/blob/master/src/components/TableLite.vue) (because I am committed twice)?

Download the [example](https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/Filter2.vue) and edit row 35 to like it.
```
for (let i = 0; i < 20; i++) {
  fakeData.push({
    id: i,
    name: parseFloat((Math.random() * (999.9 - 1.0) + 1.0).toFixed(3)).toString(),
    email: "test" + i + "@example.com",
 });
}
```

**Comment by linmasahiro** [comment]
Hi, I closed this issue. If any questions, reopen it. thx.
