### ISSUE TITLE
Ability to customized look

### ISSUE THREAD

**Issue by bolerio** [linmasahiro/vue3-table-lite#9]
Just being able to specify a CSS class for the various elements would be enough. 

Or is it possible already to customize look?

**Comment by linmasahiro** [comment]
Hi, @bolerio 
No, if you install it by NPM, you can't customize any design on this version. But! Maybe you can download [this file](https://github.com/linmasahiro/vue3-table-lite/blob/master/src/components/TableLite.vue) and change style sheet to customize design.

**Comment by linmasahiro** [comment]
I am closing this issue. If you still have problem, reopen the issue.

**Comment by linmasahiro** [comment]
Hi @bolerio, I am added styling features for v1.1.5.
https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/CustomizeStyle.vue

**Comment by PCes83** [comment]
Hi,
Thanks to class, we can style and add custom css

But my problem is the opposite: 
When using your component into existing styled project (for example, where bootstrap is used), your embeded css will override default template css.

I would be great to be able to leave embeded css away

Thanks

**Comment by linmasahiro** [comment]
Hi, @PCes83 
I used `<style scope>` tag to styling my component, because I not hope override it from outside style.
If you need override the embedded style, you can use `::v-deep` to override it. Please reference [this](https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/CustomizeStyle2.vue). 

※ If you want styling header/column only, I already added new options to styling they, ref [this issue](https://github.com/linmasahiro/vue3-table-lite/issues/32#issuecomment-1068625467)
